@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/MooseX-NiftyDelegation/project>
	deps:runtime-requirement         [ deps:on "Moose 2.00"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "thanks 0.001"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Sub::Exporter"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

