# This file provides instructions for packaging.

`MooseX-NiftyDelegation`
	perl_version_from m`MooseX::NiftyDelegation`;
	version_from      m`MooseX::NiftyDelegation`;
	readme_from       m`MooseX::NiftyDelegation`;
	test_requires     p`Test::More 0.61` ;
	.

